project:
  type: website

website:
  title: "Pratham Kabra"
  navbar:
    left:
      - text: Projects
        file: projects.qmd
      - text: About
        file: about.qmd
      - text: Experiences
        file: experiences.qmd
      - text: Skills
        file: skills.qmd    
  

format:
  html:
    theme: cosmo
    css: styles.css




  page-footer:
    left: |   
      <a href="https://www.linkedin.com/in/prathamkabra/" target="_blank">
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" alt="LinkedIn" width="30" style="vertical-align:middle;"/>
      </a>
      <a href="https://github.com/PrathamKabra" target="_blank" style="margin-left:10px;">
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" alt="GitHub" width="30" style="vertical-align:middle;"/>
      </a>
      <a href="mailto:prathamk@bu.edu" target="_blank">
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg" alt="Gmail" width="30" style="vertical-align:middle;"/>
      </a> 