project:
  type: website

website:
  title: "Pratham Kabra"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Projects
        file: projects.qmd
      - text: About
        file: about.qmd

